---
linktitle: I got sick!
weight: 7
icon: code
icon_pack: fas

# Page metadata.
title: I got Covid!  Now what?
date: "2020-08-24T00:00:00Z"
type: book  # Do not modify.
---

** Positive Covid test or Covid Symptoms

If you tested positive for Covid, you are required to isolate yourself.
You have two choices.

1. If you still feel okay, we invited you to participate remotely according to
   option 1 of [[{{< relref "/docs/getting-started/remote-students" >}}][the remote student protocol]].
2. If you do not feel okay, then this counts as an excused absense.  Notify the
   instructor using this url:
   https://forms.gle/ibmkT3vKaGFuoiyX8  Also notifiy your POGIL/in-class group!
3. We have updated the policy to allow 3 weeks of extension; this should cover
   most Covid situations, given that you are all vaccinated.

** Flu and other illnesses

If you have a fever more than 100 degrees, or if you are coughing/sneezing, then
you should stay home and not infect other people.  Follow the Covid protocol
above in such cases.  Report your absence at https://forms.gle/ibmkT3vKaGFuoiyX8

If your fever is less than that and are not coughing, then it is up to you.
